STAFF_NAMES = [
    "Evans Amanor Acheampong",
    "Frank Okyere Larbi",
    "Daniel Owusu Larbi",
    "Happy Nyarko",
    "Deborah Otuo Twumasi",
    "Ruth Opoku-Mensah",
    "Yaw Obeng Manu",
    "Richard Yankyerah",
    "Miracle Adjei",
    "Harry Nana Frimpong",
    "Mabel Faith Djaba",
    "Winifred Dede Addo",
    "Joseph Asamoah Omono",
    "Judith Waki",
    "Precious Dzotsi",
    "Emmanuel Addo Adonteng",
    "Eric Sam",
    "George Osei",
    "Marcel Y. Semondji",
    "Frederick Osei-Kuffour",
    "Emmanuel Okoe Yeboah",
    "Michael Ahiawotsiah",
    "Goka Samuel Nelson",
    "Lawrence N.Y. Amenyo",
    "Michael Adu",
    "Victoria Owusuwaa Amponsah",
]